name: Create new realease
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: install fuse and libfuse2
      run: sudo apt install fuse libfuse2

    - name: Get pkg2appimage
      run: |
        set -x
        curl --location -o pkg2appimage https://github.com/AppImageCommunity/pkg2appimage/releases/download/continuous/pkg2appimage-1807-x86_64.AppImage
        chmod +x pkg2appimage
        ls -lah

    - name: Make AppImage
      run: |
        set -x
        ./pkg2appimage Authy.yml
        ls -lahR

        cd out/
        fileName=$(ls Authy*.AppImage) 
        echo "fileName: $fileName"
        fileNameNew=$(echo "$fileName" | sed 's/.AppImage//')
        mv "$fileName" "${fileNameNew}-1_JB.AppImage"
        md5sum "${fileNameNew}-1_JB.AppImage" > "${fileNameNew}-1_JB.AppImage.md5"
        ls -lahR
        cd ../

    # Build - Error: Resource not accessible by integration
    # Change Settings -> Actions -> General -> Workflow Permissions to allow read and write:
    # https://github.com/actions/first-interaction/issues/10#issuecomment-1506118886

    # https://github.com/marketplace/actions/upload-to-github-release
    - uses: xresloader/upload-to-github-release@main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          file: "out/Authy*.AppImage; out/Authy*.md5"
          #delete_file: "random-name-*.txt;random-*.txt"
          release_id: ${{ steps.create_release.outputs.id }}
          #overwrite: true
          verbose: true
          #tags: true
          draft: false
