name: Create new realease

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: install fuse and libfuse2
      run: sudo apt install fuse libfuse2

    - name: Get pkg2appimage
      run: |
        set -x
        curl --location -o pkg2appimage https://github.com/AppImageCommunity/pkg2appimage/releases/download/continuous/pkg2appimage--x86_64.AppImage
        chmod +x pkg2appimage
        ls -lah

    - name: Make AppImage
      run: |
        set -x
        ./pkg2appimage Authy.yml
        ls -lah

        version=$(grep -o "Authy:.*" README.md | cut -d ' ' -f2)
        echo "Authy version: $version"
        
        cd out/
        fileName=$(ls Authy*.AppImage) 
        echo "fileName: $fileName"
        fileNameNew=$(echo "$fileName" | sed 's/.AppImage//')
        fileNameNew=$(echo "$fileNameNew" | cut -d'-' -f2-)
        fileNameFinal="Authy_Desktop-${version}${fileNameNew}-1_JB.AppImage"

        mv "$fileName" "$fileNameFinal"
        md5sum "$fileNameFinal" > "${fileNameFinal}.md5"
        ls -lah
        cd ../

    # Build - Error: Resource not accessible by integration
    # Change Settings -> Actions -> General -> Workflow Permissions to allow read and write:
    # https://github.com/actions/first-interaction/issues/10#issuecomment-1506118886

    # https://github.com/marketplace/actions/upload-to-github-release
    - uses: xresloader/upload-to-github-release@main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          file: "out/Authy*.AppImage; out/Authy*.md5"
          #delete_file: "random-name-*.txt;random-*.txt"
          release_id: ${{ steps.create_release.outputs.id }}
          #overwrite: true
          verbose: true
          #tags: true
          draft: false
          default_release_name: "Authy V in AppImage"

